name: "Deploy Backend API"
env:
  REPO_NAME: blog_manager

on:
  push:
    branches:
      - main
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use NodeJS 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set npm environment variables
        run: |
          echo "VUE_APP_API=${{ secrets.VUE_APP_API }}" >> $GITHUB_ENV
          echo "VUE_APP_BASE_URL=${{ secrets.VUE_APP_BASE_URL }}" >> $GITHUB_ENV

      
      - name: Install Frontend dependencies
        run: |
          cd frontend
          npm install 
      - name: Build frontend
        run: |
          cd frontend
          npm run build
      
      - name: Deploy Frontend to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.REMOTE_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USERNAME }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "frontend/dist/"
          TARGET: "/var/www/blogfrontend"
          SCRIPT: |
            nginx -s reload
            
      - name: Run remote scripts
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          script: |
            echo 'export SYS_GITHUB_TOKEN=${{ secrets.SYS_GITHUB_TOKEN }}' >> ~/.bashrc
            echo 'export SYS_BLOG_REPO=${{ secrets.SYS_BLOG_REPO }}' >> ~/.bashrc
            echo 'export SYS_LOGIN_USERNAME=${{ secrets.SYS_LOGIN_USERNAME }}' >> ~/.bashrc
            echo 'export SYS_LOGIN_PASSWORD=${{ secrets.SYS_LOGIN_PASSWORD }}' >> ~/.bashrc
            echo 'export SYS_SMTP_HOST=${{ secrets.SYS_SMTP_HOST }}' >> ~/.bashrc
            echo 'export SYS_SMTP_USER=${{ secrets.SYS_SMTP_USER }}' >> ~/.bashrc
            echo 'export SYS_SMTP_PASSWORD=${{ secrets.SYS_SMTP_PASSWORD }}' >> ~/.bashrc
            echo 'export SYS_SMTP_PORT=${{ secrets.SYS_SMTP_PORT }}' >> ~/.bashrc
            echo 'export SYS_EMAILS_FROM_EMAIL=${{ secrets.SYS_EMAILS_FROM_EMAIL }}' >> ~/.bashrc

            source ~/.bashrc

            ls -l
            rm -rf blog_manager
            git clone https://${{ secrets.SYS_GITHUB_TOKEN }}@github.com/phil616/blog_manager.git
            cd blog_manager
            su root
            bash production_build.sh
          

